// <auto-generated />
namespace _500Dishes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _500dishes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_500dishes));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201102235_500dishes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
